config/routes.rb
Rails.application.routes.draw do

  get 'images/new'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: "pages#index"

  get 'pages/contacts'
  get 'pages/about'
  get 'pages/sponsors'

  resources :posts do
    resources :postcomments
   end

resources :photos do 
    member do 
      get :vote
    end
  end
  
resources :images do
    member do
      get :voteforphoto
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :photos ,dependent: :destroy

end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
	belongs_to :user

	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/default.png"
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/photo.rb
class Photo < ApplicationRecord
	mount_uploader :photo, PhotoUploader

	belongs_to :user
	belongs_to :category
	has_many :votes, dependent: :destroy

end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :postcomment, dependent: :destroy
	validates :title,:body, presence: true
	validates :title, length: { in: 3..20 }

	mount_uploader :photo, PhotoUploader

end

app/models/postcomment.rb
class Postcomment < ApplicationRecord
	belongs_to :user
	belongs_to :post

	validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy
  has_many :postcomments, dependent: :destroy
  has_many :photos, dependent: :destroy
  has_many :images, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :voteforphotos, dependent: :destroy


  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/default.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  validates :nickname, :email, :password, :password_confirmation, presence: true
  validates :nickname, length: { in: 6..20 }
  validates :email, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
end

app/models/vote.rb
class Vote < ApplicationRecord
	belongs_to :user
	belongs_to :photo
end

app/models/vote_for_photo.rb
class VoteForPhoto < ApplicationRecord
  belongs_to :user
  belongs_to :image
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
before_action :authenticate_user!
before_action :image_set, only:[:destroy, :vote]

	def index
    	@images = Image.all
    	@like = {}
    	@images.each do |image|
      		@voteforphotos = VoteForPhoto.where(image_id: image.id).sum(:like)
      		@like[image.id] = @voteforphotos
    	end
  	end

	def new

	end

	def create
		@user = current_user

		if params[:images]
			params[:images].each {|image|
				@files = @user.images.create(image: image)}
		end
		redirect_to images_path
	end

	def destroy
    	@image.destroy
    	redirect_to images_path
    end

    def voteforphoto
    @image = Image.find(params[:id])
    @voteforphoto = VoteForPhoto.where(user_id: current_user.id, image_id: @image.id).first
    if @voteforphoto == nil
       @like = 1
       VoteForPhoto.create(user_id: current_user.id, image_id: @image.id, like: @like)
     elsif @voteforphoto.like == 0
       @voteforphoto.update(like: @voteforphoto.like + 1)
     else
       @voteforphoto.update(like: @voteforphoto.like - 1)
    end
    redirect_to images_path
  end

private

def image_params
	params.require(:images).permit(:user_id, :image)
end

def image_set
    pp @image = Image.find(params[:id])
end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	pp @posts = Post.all
  end

   def about
 
   end

   def contacts
 
   end

   def sponsors
 
   end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

before_action :authenticate_user!
before_action :set_post, only:[:show, :edit, :update, :destroy]
before_action :check_user, only: :edit

  def show
    pp @comment = @post.postcomment
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to root_path
    else 
    render 'new'  
    end 
      
  end

  def edit

  end

  def update
    @post.update(post_params)
    redirect_to root_path
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

private

  def post_params
    params.require(:post).permit(:user_id, :title, :body, :photo)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def check_user
      if current_user.id != @post.user_id and !current_user.admin?
        redirect_to root_path, danger: 'У вас немаэ прав!'
      end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/postcomments_helper.rb
module PostcommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Solaris</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <style>
    /* Design by http://www.dreamtemplate.com */
@charset "utf-8";
body {
  margin:0;
  padding:0;
  width:100%;
  color:#cccccc;
  font:normal 12px/1.5em "Liberation sans", Arial, Helvetica, sans-serif;
  background:#555 repeat-x left top;
}
html, .main {
  padding:0;
  margin:0;
}

.clr {
  clear:both;
  padding:0;
  margin:0;
  width:100%;
  font-size:0;
  line-height:0;
}
h2 {
  margin:8px 0;
  padding:8px 0;
  font-size:25px;
  font-weight:normal;
  color:#353c46;
}
p {
  margin:8px 0;
  padding:0 0 8px 0;
}
a {
  color:#ffee5f;
  text-decoration:underline;
}
.header, .content, .menu_nav, .fbg, .footer, form, ol, ol li, ul, .content .mainbar, .content .sidebar {
  margin:0;
  padding:0;
}

.header_resize {
  margin:0 auto;
  padding:0;
  width:960px;
}
.logo {
  margin:0;
  padding:0;
  float:left;
  width:auto;
  height:146px;
}
h1 {
  margin:0;
  padding:40px 0 0;
  font-size:60px;
  font-weight:normal;
  line-height:1.2em;
  text-transform:none;
  text-align:left;
}
h1 a, h1 a:hover {
  color:#fff;
  text-decoration:none;
}
h1 span {
}
h1 small {
  display:block;
  margin:-8px 0;
  font-size:32px;
  line-height:1.2em;
  letter-spacing:normal;
  text-transform:none;
  color:#fff;
}

.menu_nav {
  margin:0 auto;
  padding:0;
  height:54px;
  float:right;
}
.menu_nav ul {
  list-style:none;
  padding:0;
  height:54px;
  float:left;
}
.menu_nav ul li {
  margin:0;
  padding:0;
  float:left;
}
.menu_nav ul li a {
  display:block;
  margin:0;
  padding:16px 0 0;
  width:192px;
  height:54px;
  font-size:24px;
  line-height:30px;
  font-weight:normal;
  color:#fff;
  text-decoration:none;
  text-transform:none;
  text-align:center;
  background:none;
}
.menu_nav ul li.active a, .menu_nav ul li a:hover {
  text-decoration:none;
  color:#fff;
  background:#ffc53c;
}
.content {
  padding:0;
}
.content_resize {
  margin:0 auto;
  padding:18px 0;
  width:960px;
}
.content .mainbar {
  margin:0;
  padding:0 0 0 20px;
  float:left;
  width:620px;
}
.content .mainbar h2 {
  margin-bottom:0;
  padding-bottom:0;
  font-size:25px;
  line-height:1.2em;
  color:#fff;
}
.content .mainbar div.img {
  padding:12px 0;
  float:left;
}
.content .mainbar img {
}
.content .mainbar img.fl {
  margin:0;
  padding:0;
  background:#fff;
  border:none;
}
.content .mainbar .post_content {
}
.content .mainbar .post_content strong {
  color:#c7c7c7;
}
.content .sidebar {
  padding:0;
  float:right;
  width:260px;
}
.content .sidebar .gadget {
  margin:0 0 12px;
  padding:8px 20px 24px;
}
.content .sidebar h2 {
  color:#fff;
  text-transform:none;
}
ul.sb_menu, ul.ex_menu {
  margin:0;
  padding:0;
  list-style:none;
  color:#929292;
}
ul.sb_menu li, ul.ex_menu li {
  margin:0;
}
ul.sb_menu li {
  padding:8px 0;
  width:220px;
}
ul.ex_menu li {
  padding:4px 0;
}
ul.sb_menu li a {
  color:#929292;
  text-decoration:none;
  margin-left:-16px;
  padding:4px 8px 4px 16px;
}
ul.ex_menu li a {
  font-weight:bold;
  color:#c7c7c7;
  text-decoration:none;
}
ul.sb_menu li a:hover, ul.ex_menu li a:hover {
  color:#ffee5f;
  font-weight:bold;
  text-decoration:underline;
}
p.spec {
  padding:0 0 16px;
}
p.infopost {
  margin-bottom:0;
  padding:8px 12px;
  color:#929292;
  background:#494949;
}
p.infopost a {
  padding:0 2px;
  color:#ffee5f;
  text-decoration:underline;
}
.content .mainbar a.com {
  margin:-8px -12px;
  padding:8px 12px;
  float:right;
  font-weight:normal;
  text-decoration:none;
  color:#8b8b8b;
  background:#1b1b1b;
}
.content .mainbar a.com:hover {
  text-decoration:none;
}
.content .mainbar a.com span {
  padding-left:4px;
  font-weight:bold;
  color:#ffee5f;
}
.content .mainbar a.rm {
  float:right;
  margin:0 0 16px;
  padding:0;
  font-weight:normal;
  text-transform:lowercase;
  color:#ffee5f;
  text-decoration:underline;
  text-align:center;
  background:none;
}
.content p.pages {
  margin:0;
  padding:24px 0;
  font-size:11px;
  color:#929292;
  text-align:left;
}
.content p.pages span, .content p.pages a {
  padding:8px 12px;
  text-decoration:none;
  background:none;
}
.content p.pages span, .content p.pages a:hover {
  color:#929292;
  background:#3b3b3b;
}
.content p.pages a {
  color:#929292;
}
.content p.pages small {
  font-size:12px;
  float:right;
}
.content .mainbar .comment {
  margin:0;
  padding:16px 0 0 0;
}
.content .mainbar .comment img.userpic {
  border:1px solid #dedede;
  margin:10px 16px 0 0;
  padding:0;
  float:left;
}
.fbg {
  background:#555 repeat-x left bottom;
}
.fbg_resize {
  margin:0 auto;
  width:920px;
  padding:16px 20px;
  color:#6e6e6e;
  background:#fff;
}
.fbg h2 {
  color:#3f3f3f;
  padding-bottom:24px;
}
.fbg img.gal {
  margin:0 8px 8px 0;
  padding:0;
  border:none;
}
.fbg .col {
  margin:0;
  float:left;
}
.fbg .c1 {
  padding:0 16px 0 0;
  width:280px;
}
.fbg .c2 {
  padding:0 36px 0 16px;
  width:280px;
}
.fbg .c3 {
  padding:0 0 0 16px;
  width:274px;
}
.fbg .fbg_ul {
  margin:0;
  padding:0;
  list-style:none;
}
.fbg .fbg_ul li {
  margin:0;
  padding:0;
  list-style:none;
}

.fbg .fbg_ul li a:hover {
  color:#ffa41a;
  text-decoration:underline;
}
.fbg p.contact_info {
  line-height:1.8em;
}
.fbg p.contact_info a {
  color:#ffa41a;
  text-decoration:underline;
}
.fbg p.contact_info span {
  display:block;
  float:left;
  width:74px;
  font-weight:bold;
  color:#3f3f3f;
}
ol {
  list-style:none;
}
ol li {
  display:block;
  clear:both;
}
ol li label {
  display:block;
  margin:0;
  padding:16px 0 0 0;
}
ol li input.text {
  width:480px;
  border:1px solid #c0c0c0;
  margin:0;
  padding:5px 2px;
  height:16px;
  background-color:#fff;
}
ol li textarea {
  width:480px;
  border:1px solid #c0c0c0;
  margin:0;
  padding:2px;
  background-color:#fff;
}
ol li .send {
  margin:16px 0 0 0;
}

a {
  outline:none;
}
.clearfix:after, .clearfix:before{
  content: "";
  display: block;
  clear: both;
}
.clearfix{
  background-color: #3b3b3b;
}
.header{
  background-color: #ffc53c;
  text-align: center;
  max-height: 450px;
  margin-bottom: 200px;
}
  img{
    max-width: 150%;
  }
  .img{
    transform: translateY(15px);
    height: 450px;
    border: 4px solid white;
  }

  .content {
    float: left;
  }

  .sidebar {
    float: left;
    margin-top: 55px;
  }

  .footer{
    font-size: 15px;
    background:#ffc63d url(footer_bg.gif) repeat-x left bottom;
    color: black;
    text-align: center;
    line-height: 60px;
  }


  </style>

  <body>

<div class="main">
  <div class="header">
        <div class="menu_nav col-lg-12 clearfix">
          <ul>
            <li><%= link_to 'Головна сторінка', root_path %></li>
            <li><%= link_to 'Галерея', photos_path %></li>
            <li><%= link_to 'Про сайт', pages_about_path %></li>
            <li><%= link_to 'Контакти', pages_contacts_path %></li>

        <% if user_signed_in? %>
            <li class="nav-item " style="margin-left: 331px">
              <%=link_to "Вихід", destroy_user_session_path, method:  :delete, class: "nav-link" %>
            </li>
        <% else %>
            <li class="nav-item" style="margin-left: 139px">
              <%= link_to "Вхід", new_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Реєстрація", new_user_registration_path, class: "nav-link" %>
            </li>
        <% end %>
          </ul> 
      </div>
    <div class="header_resize">
      <div class="clr"></div>
      <div class="logo">
        <h1 style="color: black">Solaris<span>SunSystems</span> <small>Принесемо тепло у кожен дім</small></h1>
      </div>
        <img src="https://cdni.rt.com/files/news/2f/a7/40/00/10.si.jpg" class="img">
      <div class="clr"></div>
      </div>
    </div>

      

    <div class="container col-md-12">
      <div class="content col-md-10">
        <%= yield %>
      </div>
        <div class="sidebar col-md-2">
          <h2><b>Сайд-бар</b></h2>
          <ul style="font-size: 15px">
            <li><%= link_to 'Головна', root_path %></li>
            <li><%= link_to 'Cпонсори', pages_sponsors_path %></li>
            <li><%= link_to 'Галерея', photos_path %></li>
          </ul>
          <br>
        </div>
        <%= link_to 'Cтворити новину', new_post_path, class: 'btn btn-info' %>
      </div>  

  <div class="footer col-md-12">
    Created by Ansatasia Betsa
  </div>

  </body>
</html>

app/views/pages/about.html.erb
<h1 style="text-align: center">Новинки альтернативної енергетики</h1>
<div class="container">
  <div class="row">
    <div class="col-xs-6">
    	<a href="https://teknoblog.ru/2017/10/31/84035" target="_blank">
    		<p style="font-size: 20px; color: white;">Глава Tesla предрекает возврат к Средневековью без использования ВИЭ</p>
		<img src="https://cdn.teknoblog.ru/wp-content/uploads/2016/10/Mask_Tesla-768x573.jpg" style="width: 180px; height: 134px;">
		</a>
	</div>
    <div class="col-xs-6">
    	<a href="https://teknoblog.ru/2017/09/19/82400" target="_blank"><p style="font-size: 20px; color: white">В Дубаи построят крупнейшую в мире солнечную электростанцию</p>
    	<img src="https://cdn.teknoblog.ru/wp-content/uploads/2016/06/Oai-Sol.jpg" style="width: 200px; height: 134px">
    	</a>
	</div>
  </div>

  <div class="row">
    <div class="col-xs-6">
    	<a href="https://teknoblog.ru/2017/08/28/81644" target="_blank">
    		<p style="font-size: 20px; color: white;">В Великобритании появится свой уникальный “солнечный” городок</p>
		<img src="https://cdn.teknoblog.ru/wp-content/uploads/2017/08/sol-02.jpg" style="width: 180px; height: 134px">
		</a>
	</div>
    <div class="col-xs-6">
    	<a href="https://teknoblog.ru/2017/08/12/81067" target="_blank"><p style="font-size: 20px; color: white">Ветропарк с самыми большими в мире турбинами будет построен в Великобритании</p>
    	<img src="https://cdn.teknoblog.ru/wp-content/uploads/2015/07/veter-ES-morskaya.jpg" style="width: 200px; height: 134px">
    	</a>
	</div>
  </div>

  <div class="row">
    <div class="col-xs-6">
    	<a href="https://teknoblog.ru/2017/07/15/80213" target="_blank">
    		<p style="font-size: 20px; color: white;">Австралийские солнечные мини-станции обещают революцию в “зеленой” энергетике</p>
		<img src="https://cdn.teknoblog.ru/wp-content/uploads/2017/07/sol-9.jpg" style="width: 180px; height: 134px">
		</a>
	</div>
    <div class="col-xs-6">
    	<a href="https://teknoblog.ru/2017/07/12/80127" target="_blank"><p style="font-size: 20px; color: white">Уже 100 компаний “помешались” на “зеленой” инициативе</p>
    	<img src="https://cdn.teknoblog.ru/wp-content/uploads/2016/09/Energia-veter-sol.jpg" style="width: 200px; height: 134px">
    	</a>
	</div>
  </div>

  <div class="row">
    <div class="col-xs-6">
    	<a href="https://www.gazeta.ru/tech/2016/02/02/8052713/solar_energy.shtml" target="_blank">
    		<p style="font-size: 20px; color: white;">Что, если не нефть</p>
		<img src="https://img.gazeta.ru/files3/85/8053085/shutterstock_60600820-pic4_zoom-1500x1500-69828.jpg" style="width: 180px; height: 134px">
		</a>
	</div>
    <div class="col-xs-6">
    	<a href="https://teknoblog.ru/2017/07/12/80127" target="_blank"><p style="font-size: 20px; color: white">Уже 100 компаний “помешались” на “зеленой” инициативе</p>
    	<img src="https://cdn.teknoblog.ru/wp-content/uploads/2016/09/Energia-veter-sol.jpg" style="width: 200px; height: 134px">
    	</a>
	</div>
  </div>
</div>

app/views/pages/contacts.html.erb
<p><h1 style="color: white; text-align: center;">Наші спонсори</h1></p>
<a href="https://teknoblog.ru/tag/%D0%B0%D0%BB%D1%8C%D1%82%D0%B5%D1%80%D0%BD%D0%B0%D1%82%D0%B8%D0%B2%D0%BD%D0%B0%D1%8F-%D1%8D%D0%BD%D0%B5%D1%80%D0%B3%D0%B5%D1%82%D0%B8%D0%BA%D0%B0" target="_blank"><img src="https://cdn.teknoblog.ru/wp-content/uploads/logo_.png"></a>
<a href="https://www.gazeta.ru/tech/2016/02/02/8052713/solar_energy.shtml" target="_blank"><img src="https://static.gazeta.ru/nm2015/i/logo_gazeta.svg" style="width: 300px"></a>
<a href="https://hi-news.ru/tag/alternativnaya-energiya" target="_blank"><img src="https://hi-news.ru/wp-content/themes/101media/img/logo-2015@2x.png"></a>
<div class="container-fluid">
<h1 style="text-align: center;">Нас можна знайти:</h1>
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2638.126747425574!2d22.262505915452028!3d48.60741707926372!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x473918fb01dc5047%3A0xa8908e1ac4a6c881!2z0KTQsNC60YPQu9GM0YLQtdGCINC40L3RhNC-0YDQvNCw0YbQuNC-0L3QvdGL0YUg0YLQtdGF0L3QvtC70L7Qs9C40Lkg0KPQttCd0KM!5e0!3m2!1sru!2sua!4v1514146529568" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen></iframe>
</div>

app/views/pages/index.html.erb
<style type="text/css">
	.post-header{
		display: flex;
		justify-content: space-between;
		background-color: #333;
		color: white;
		align-items: center;
		padding-right: 15px;
		margin: 5	px 0;	
	}

	h2 {
		margin-top: 30px;
	}

	h2>a,h2>a:visited{
		color: orange;
		transition: all 400ms

	}
	h2>a:hover{
		color: white;
		font-size: 30px
	}

	div.img-show {
		margin: 10px 0 5px 50px;
	}

</style>


<% @posts.each do |post| %>

 	<div class="content-text col-md-10">

		<h2><%= link_to post.title , post_path(post.id)%></h2>
		<div class="post-header">

			<div><%= image_tag post.user.avatar.url, width: 30, height: 30 %>
				
				Author:  <%= post.user.nickname %> 
			</div>
			<div>
			Created at:<%= post.created_at %>
			<% if current_user != nil and current_user.id == post.user_id %>
			  |
			  <%= link_to "Edit", edit_post_path(post.id) %>
			  |
			  <%= link_to "Delete", post_path(post.id), data: {confirm: 'Are you sure?'}, method: :delete %>
			<% end %>
			</div>
			
		</div>
			<div class="img-show">
			<%= image_tag post.photo.url, width: '90%', height: 300 if post.photo? %></div>
			<%= sanitize(post.body) %>
	</div>
 <% end %>

app/views/pages/sponsors.html.erb
<p><h1 style="color: white; text-align: center;">Наші спонсори</h1></p>
<a href="https://teknoblog.ru/tag/%D0%B0%D0%BB%D1%8C%D1%82%D0%B5%D1%80%D0%BD%D0%B0%D1%82%D0%B8%D0%B2%D0%BD%D0%B0%D1%8F-%D1%8D%D0%BD%D0%B5%D1%80%D0%B3%D0%B5%D1%82%D0%B8%D0%BA%D0%B0" target="_blank"><img src="https://cdn.teknoblog.ru/wp-content/uploads/logo_.png"></a>
<a href="https://www.gazeta.ru/tech/2016/02/02/8052713/solar_energy.shtml" target="_blank"><img src="https://static.gazeta.ru/nm2015/i/logo_gazeta.svg" style="width: 300px"></a>
<a href="https://hi-news.ru/tag/alternativnaya-energiya" target="_blank"><img src="https://hi-news.ru/wp-content/themes/101media/img/logo-2015@2x.png"></a>
<div class="container-fluid">